# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conversation.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_conversation(object):
    def setupUi(self, conversation):
        conversation.setObjectName("conversation")
        conversation.resize(305, 467)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/juliet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        conversation.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(conversation)
        self.centralwidget.setObjectName("centralwidget")

        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.settings.setObjectName("Settingswindow")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 101, 20))
        self.label.setObjectName("label")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 410, 211, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 410, 41, 23))
        self.pushButton.setObjectName("pushButton")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(56, 82, 191, 121))
        self.label_2.setObjectName("label_2")

        conversation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(conversation)
        self.statusbar.setObjectName("statusbar")
        conversation.setStatusBar(self.statusbar)

        self.retranslateUi(conversation)
        QtCore.QMetaObject.connectSlotsByName(conversation)

    def retranslateUi(self, conversation):
        _translate = QtCore.QCoreApplication.translate
        conversation.setWindowTitle(_translate("conversation", "Juliet"))
        self.label.setText(_translate("conversation", "Conversation"))
        self.pushButton.setText(_translate("conversation", "Send"))
        self.settings.setText(_translate("conversation", "Settings"))
        self.label_2.setText(_translate("conversation", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    conversation = QtWidgets.QMainWindow()
    ui = Ui_conversation()
    ui.setupUi(conversation)
    conversation.show()
    sys.exit(app.exec_())
