# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def checkboxstate(self):
        state1 = True

        if not state1:
            self.checkBox.setChecked(True)
        else:
            self.checkBox.setChecked(True)
            self.checkBox_2.setChecked(False)


    def checkboxstate2(self):
        state1 = self.checkBox_2.isChecked()

        if not state1:
            self.checkBox_2.setChecked(True)
        else:
            self.checkBox_2.setChecked(True)
            self.checkBox.setChecked(False)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(255, 320)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/juliet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:#730013")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")



        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 60, 200, 50))
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setFamily("Geometr415 Blk BT")
        font.setBold(True)
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #8cffec")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 150, 181, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 200, 16))
        self.label_2.setObjectName("label_2")
        font = QtGui.QFont()
        font.setFamily("Geometr415 Blk BT")
        font.setBold(True)
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #8cffec")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 210, 200, 16))
        self.label_3.setObjectName("label_3")
        font = QtGui.QFont()
        font.setFamily("Geometr415 Blk BT")
        font.setBold(True)
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #8cffec")

        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(50, 250, 70, 17))
        self.checkBox.setObjectName("checkBox")
        font = QtGui.QFont()
        font.setFamily("Geometr415 Blk BT")
        font.setBold(True)
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: #8cffec")
        self.checkBox.setChecked(True)
        self.checkBox.clicked.connect(self.checkboxstate)

        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 250, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        font = QtGui.QFont()
        font.setFamily("Geometr415 Blk BT")
        font.setBold(True)
        font.setPointSize(11)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: #8cffec")
        self.checkBox_2.setChecked(False)
        self.checkBox_2.clicked.connect(self.checkboxstate2)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 275, 75, 23))
        self.pushButton_2.setObjectName("Save")
        font = QtGui.QFont()
        font.setFamily("Geometr415 Blk BT")
        font.setBold(True)
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: #8cffec")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Juliet"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.label_2.setText(_translate("MainWindow", "What can i call you"))
        self.label_3.setText(_translate("MainWindow", "Select a Voice"))
        self.checkBox.setText(_translate("MainWindow", "Zira"))
        self.checkBox_2.setText(_translate("MainWindow", "Mark"))
        self.pushButton_2.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
